changelog:
  categories:
    - title: Features
      labels:
        - enhancement
    - title: Types Changes
      labels:
        - types
    - title: バグの修正
      labels:
        - bug
    - title: その他の変更点
      labels:
        - '*'
